compilers:
- compiler:
    spec: intel@2024.2.1
    paths:
      cc: /apps/oneapi/compiler/2022.0.2/linux/bin/intel64/icx
      cxx: /apps/oneapi/compiler/2022.0.2/linux/bin/intel64/icpc
      f77: /apps/oneapi/compiler/2022.0.2/linux/bin/intel64/ifort
      fc: /apps/oneapi/compiler/2022.0.2/linux/bin/intel64/ifort
    flags: {}
    operating_system: rocky9
    modules:
    - intel-oneapi-compilers/2024.2.1
    environment:
      prepend_path:
        PATH: '/usr/bin'
        LD_LIBRARY_PATH: '/usr/lib64'
        CPATH: '/usr/include/c++/11'
    extra_rpaths: []
- compiler:
    spec: gcc@11.4.1
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc:  /usr/bin/gfortran
    flags: {}
    operating_system: rocky9
    environment: {}
    extra_rpaths: []
