mirrors:
  local-source:
    fetch:
      url: file:///collab1/data/Richard.Grubin/contrib/spack-stack-rocky9/mirror
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///collab1/data/Richard.Grubin/contrib/spack-stack-rocky9/mirror
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
