packages:
  all:
    # To support hecflow01
    # target: [AMD EPYC]
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.2
      prefix: /usr
  bash:
    externals:
    - spec: bash@5.1.8
      prefix: /usr
  berkeley-db:
  # not installed per: dnf list installed|grep -i db-devel
    externals:
    #- spec: berkeley-db@5.3.21
    - spec: berkeley-db@18.1.40
      prefix: /apps/spack-2024-09/linux-rocky9-x86_64/gcc-11.4.1/berkeley-db-18.1.40-tetbmt6446oglhqm4dnhpybup6ltpnno
  #bzip2:
  #  externals:
  #  - spec: bzip2@1.0.8
  #    prefix: /usr
  cpio:
    externals:
    - spec: cpio@2.13.90
      prefix: /usr
  curl:
    externals:
    - spec: curl@7.61.1
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.7-12
      prefix: /usr
  doxygen:
  # not installed per: dnf list installed | grep -i doxygen
    externals:
    - spec: doxygen@1.11.0+graphviz~mscgen
      prefix: /apps/spack-2024-09/linux-rocky9-x86_64/gcc-11.4.1/doxygen-1.11.0-dbhxblaakcrhvmlrbgixvapnagjb2vkx
  # ecflow::
  #   buildable: False
  #   externals:
  #   - spec: ecflow@5.5.3+ui+static_boost
  #     prefix: /apps/ecflow/5.5.3
  #     modules:
  #     - ecflow/5.5.3
  file:
    externals:
    - spec: file@5.39
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.8.0-6
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@5.1.0
      prefix: /usr
  ghostscript:
    externals:
    - spec: ghostscript@10.03.1
      prefix: /apps/spack-2024-09/linux-rocky9-x86_64/gcc-11.4.1/ghostscript-10.03.1-womgp7wo5ax6gm3afwvf5szxy3w4ap4v
  git:
    externals:
    - spec: git@2.43.5+tcltk
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@3.2.0
      prefix: /collab1/data/Richard.Grubin/contrib/spack-stack-rocky9/git-lfs-3.2.0
      modules:
      - git-lfs/3.2.0
  gmake:
    externals:
    - spec: gmake@4.3
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
  hwloc:
    externals:
    - spec: hwloc@2.4.1-5
      prefix: /usr
  openjdk:
    externals:
    - spec: openjdk@1.8.0.412.b08-2
      prefix: /usr
  krb5:
    externals:
    - spec: krb5@1.21.1-1
      prefix: /usr
  libfuse:
    externals:
    - spec: libfuse@3.16.2
      prefix: /apps/spack-2024-09/linux-rocky9-x86_64/gcc-11.4.1/libfuse-3.16.2-ojgtqzqj77qx3dejl6w6ebfgkfxklys4
  libtirpc:
    externals:
    - spec: libtirpc@1.3.3
      prefix: /apps/spack-2024-09/linux-rocky9-x86_64/gcc-11.4.1/libtirpc-1.3.3-fpds3yq6y26a4svyiblqe6ram5js4rxf
  #libxaw:
  #  externals:
  #  - spec: libxaw@1.0.16
  #    prefix: /apps/spack-2024-09/linux-rocky9-x86_64/gcc-11.4.1/libxaw-1.0.16-i6i72n5zsfwifptwhjkuvqinzf6f3yqs
  libxcrypt:
    externals:
    - spec: libxcrypt@4.1.1-6
      prefix: /usr
  libxpm:
    externals:
    - spec: libxpm@3.5.13-10
      prefix: /usr
  # lustre:
  #   externals:
  #   - spec: lustre@2.12.5_ddn18
  #     prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.19
      prefix: /usr
  # mysql:
  #   buildable: False
  #   externals:
  #   - spec: mysql@8.0.31
  #     prefix: /collab1/data/Richard.Grubin/contrib/spack-stack-rocky9/mysql-8.0.31
  #     modules:
  #     - mysql/8.0.31
  ncurses:
    externals:
    - spec: ncurses@6.2-10.20210508+termlib abi=5
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@3.0.14
      prefix: /collab1/data/Richard.Grubin/contrib/spack-stack-rocky9/miniconda3-3.12.4
  perl:
    externals:
    - spec: perl@5.32.1~cpanm+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@1.7.3
      prefix: /usr
  rsync:
    externals:
    - spec: rsync@3.2.3
      prefix: /usr
  ruby:
    externals:
    - spec: ruby@3.2.3
      prefix: /apps/ruby/3.2.3
      modules:
      - ruby/3.2.3
  sed:
    externals:
    - spec: sed@4.8
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@7.1
      prefix: /apps/spack-2024-09/linux-rocky9-x86_64/gcc-11.4.1/texinfo-7.1-vtmy2xy3v7zn2ct4brekmagtpfbs5fmi
  texlive:
    externals:
    - spec: texlive@20220321
      prefix: /apps/spack-2024-09/linux-rocky9-x86_64/gcc-11.4.1/texlive-20220321-nwvwftavgdpph7ifqemmapdnrji33a7c
  wget:
    externals:
    - spec: wget@1.21.1
      prefix: /usr
  which:
    externals:
    - spec: which@2.21
      prefix: /usr
  xz:
    externals:
    - spec: xz@5.2.5
      prefix: /usr
  zip:
    externals:
    - spec: zip@3.0
      prefix: /usr
