packages:
  all:
    compiler:: [oneapi@2024.2.1]
    providers:
      #mpi:: [intel-oneapi-mpi@2021.13.1]
      mpi:: [intel-oneapi-mpi@2021.13]
      # Remove the next three lines to switch to intel-oneapi-mkl
      #blas:: [intel-oneapi-mkl]
      #fftw-api:: [intel-oneapi-mkl]
      #lapack:: [intel-oneapi-mkl]
  mpi:
    buildable: False
  intel-oneapi-mpi:
    buildable: False
    externals:
    #- spec: intel-oneapi-mpi@2021.13.1%oneapi@2024.2.1
    - spec: intel-oneapi-mpi@2021.13%oneapi@2024.2.1
      modules:
      - intel-oneapi-mpi@2021.13.1
      #prefix: /apps/spack-2024-09/linux-rocky9-x86_64/gcc-11.4.1/intel-oneapi-mpi-2021.13.1-aalgxlsn6mj2wsdebjjv4fl4duddijzr
      prefix: /apps/spack-2024-09/linux-rocky9-x86_64/oneapi-2024.2.1/intel-oneapi-mpi-2021.13.1-ss72gbndvat3oz22sa6lhmlbjkeabrn4
  intel-oneapi-mkl:
    # Remove buildable: False and uncomment externals section below to use intel-oneapi-mkl
    buildable: False
    externals:
    - spec: intel-oneapi-mkl@2024.2.1%oneapi@2024.2.1
      modules:
      - intel-oneapi-mkl@2024.2.1
      prefix: /apps/spack-2024-09/linux-rocky9-x86_64/oneapi-2024.2.1/intel-oneapi-mkl-2024.2.1-qycujjl4y3cipv3izc6if2gx76ah4pzh
  # DH* Remove this section to switch to intel-oneapi-mkl
  #ectrans:
  #  require::
  #  - '@1.2.0 ~mkl +fftw'
  #gsibec:
  #  require::
  #  - '@1.2.1 ~mkl'
  #py-numpy:
  #  require::
  #  - '@:1.25 ^openblas'
  # *DH
  #zlib-ng:
  #  require:
  #    - '~shared'
