packages:
  all:
    # To support hecflow01
    # target: [AMD EPYC]
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.2
      prefix: /usr
  bash:
    externals:
    - spec: bash@5.1.8
      prefix: /usr
  # berkeley-db:
  # not installed per: dnf list installed|grep -i db-devel
  #   externals:
  #   - spec: berkeley-db@5.3.21
  #     prefix: /usr
  bzip2:
    externals:
    - spec: bzip2@1.0.8
      prefix: /usr
  cpio:
    externals:
    - spec: cpio@2.13.90
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.7-12
      prefix: /usr
  # doxygen:
  # not installed per: dnf list installed | grep -i doxygen
  #   externals:
  #   - spec: doxygen@1.8.5+graphviz~mscgen
  #     prefix: /usr
  # ecflow::
  #   buildable: False
  #   externals:
  #   - spec: ecflow@5.5.3+ui+static_boost
  #     prefix: /apps/ecflow/5.5.3
  #     modules:
  #     - ecflow/5.5.3
  file:
    externals:
    - spec: file@5.39
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.8.0-6
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@5.1.0
      prefix: /usr
  # ghostscript:
  #   externals:
  #   - spec: ghostscript@9.25
  #     prefix: /usr
  git:
    externals:
    - spec: git@2.43.5+tcltk
      prefix: /usr
  # git-lfs:
  #   externals:
  #   - spec: git-lfs@2.10.0
  #     prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.3
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
  hwloc:
    externals:
    - spec: hwloc@2.4.1-5
      prefix: /usr
  openjdk:
    externals:
    - spec: openjdk@1.8.0.412.b08-2
      prefix: /usr
  krb5:
    externals:
    - spec: krb5@1.21.1-1
      prefix: /usr
  # libfuse:
  #   externals:
  #   - spec: libfuse@2.9.2
  #     prefix: /usr
  libxpm:
    externals:
    - spec: libxpm@3.5.13-10
      prefix: /usr
  # lustre:
  #   externals:
  #   - spec: lustre@2.12.5_ddn18
  #     prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.19
      prefix: /usr
  mysql:
    buildable: False
    externals:
    - spec: mysql@8.0.31
      prefix: /scratch1/NCEPDEV/global/spack-stack/apps/mysql-8.0.31
      modules:
      - mysql/8.0.31
  ncurses:
    externals:
    - spec: ncurses@6.2-10.20210508+termlib abi=5
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.32.1~cpanm+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@1.7.3
      prefix: /usr
  rsync:
    externals:
    - spec: rsync@3.2.3
      prefix: /usr
   ruby:
     externals:
     - spec: ruby@3.2.3
       prefix: /apps/ruby/3.2.3
       modules:
       - ruby/3.2.3
  sed:
    externals:
    - spec: sed@4.8
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
  # texinfo:
  #   externals:
  #   - spec: texinfo@5.1
  #     prefix: /usr
  # texlive:
  #   externals:
  #   - spec: texlive@20130530
  #     prefix: /usr
  wget:
    externals:
    - spec: wget@1.21.1
      prefix: /usr
  xz:
    externals:
    - spec: xz@5.2.5
      prefix: /usr
  zip:
    externals:
    - spec: zip@3.0
      prefix: /usr
