core_deployments:
  - template: "unified-dev"
    compilers: ["oneapi-2024.2.1"]
    packages_to_install:
    - ufs-weather-model-env
    - global-workflow-env
    - gsi-env
    - madis

#addon_deployments:
#  - template: "test-addon"
#    compilers: ["oneapi-2024.2.1"]
#    upstream: ["unified-dev"]
